# Calculate the project root from the invocation.
${projectRoot} = $(split-path -parent $(split-path -parent $(split-path -parent $SCRIPT:MyInvocation.MyCommand.Path)))
$keyRoot = "C:\Source\Product Keys"
$sn64 = "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\sn.exe"

# Sign the partially signed assemblies.
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.FluidTradeLibrary.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.FluidTradeWindows.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.BlotterDetailReport.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.BlotterViewer.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.ClientDataModel.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.ClientTradingSupport.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.DebtBlotterViewer.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.DebtHolderBlotterViewer.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.DebtHolderMatchReport.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.DebtHolderNegotiationConsole.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.DebtHolderNegotiationConsole.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.DebtHolderSettlementReport.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.DebtHolderWorkingOrderReport.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.DebtNegotiatorBlotterViewer.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.DebtNegotiatorMatchReport.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.DebtNegotiatorNegotiationConsole.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.DebtNegotiatorSettlementReport.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.DebtNegotiatorWorkingOrderReport.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.DebtPaymentReports.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.DebtWorkingOrderReport.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.DestinationOrderReport.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.DetailReports.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.EquityBlotterViewer.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.EquityWorkingOrderReport.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.ExecutionReport.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.FolderViewer.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.GuardianLibrary.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.GuardianWindows.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.MatchReport.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.NegotiationConsole.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.NegotiationService.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.SourceOrderReport.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.WorkingOrderReport.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.MessageLibrary.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.PdfControl.dll" "${keyRoot}\Key Pair.snk"
&"${sn64}" -q -R "${projectRoot}\Guardian\Client\bin\Release\FluidTrade.DetailReports.dll" "${keyRoot}\Key Pair.snk"
