//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Windows.Markup.XmlnsDefinitionAttribute("urn:schemas-fluidtrade-com:guardian:debt-holder-match-header", "FluidTrade.Guardian.Schema.DebtHolderMatchHeader")]

namespace FluidTrade.Guardian.Schema.DebtHolderMatchHeader
{
	
	
	/// <summary>
	/// This class provides the AccountNumber data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class AccountNumber : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountNumber, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountNumber> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static AccountNumber()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountNumber.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountNumber, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountNumber>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountNumber.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountNumber records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountNumber, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountNumber> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountNumber.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountNumber to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountNumber accountNumber = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountNumber)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountNumber SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountNumber accountNumber)
		{
			return accountNumber;
		}
	}
	
	/// <summary>
	/// This class provides the Address1 data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class Address1 : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address1, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address1> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static Address1()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address1.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address1, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address1>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address1.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address1 records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address1, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address1> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address1.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address1 to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address1 address1 = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address1)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address1 SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address1 address1)
		{
			return address1;
		}
	}
	
	/// <summary>
	/// This class provides the Address2 data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class Address2 : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address2, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address2> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static Address2()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address2.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address2, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address2>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address2.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address2 records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address2, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address2> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address2.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address2 to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address2 address2 = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address2)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address2 SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address2 address2)
		{
			return address2;
		}
	}
	
	/// <summary>
	/// This class provides the Blotter data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class Blotter : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Blotter, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Blotter> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static Blotter()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Blotter.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Blotter, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Blotter>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Blotter.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Blotter records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Blotter, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Blotter> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Blotter.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Blotter to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Blotter blotter = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Blotter)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Blotter SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Blotter blotter)
		{
			return blotter;
		}
	}
	
	/// <summary>
	/// This class provides the City data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class City : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.City, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.City> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static City()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.City.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.City, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.City>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.City.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.City records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.City, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.City> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.City.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.City to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.City city = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.City)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.City SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.City city)
		{
			return city;
		}
	}
	
	/// <summary>
	/// This class provides the CreatedBy data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class CreatedBy : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedBy, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedBy> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static CreatedBy()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedBy.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedBy, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedBy>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedBy.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedBy records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedBy, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedBy> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedBy.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedBy to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedBy createdBy = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedBy)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedBy SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedBy createdBy)
		{
			return createdBy;
		}
	}
	
	/// <summary>
	/// This class provides the CreatedDateTime data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class CreatedDateTime : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedDateTime, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedDateTime> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static CreatedDateTime()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedDateTime.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedDateTime, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedDateTime>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedDateTime.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedDateTime records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedDateTime, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedDateTime> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedDateTime.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedDateTime to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedDateTime createdDateTime = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedDateTime)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedDateTime SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedDateTime createdDateTime)
		{
			return createdDateTime;
		}
	}
	
	/// <summary>
	/// This class provides the AccountBalance data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class AccountBalance : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountBalance, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountBalance> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static AccountBalance()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountBalance.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountBalance, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountBalance>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountBalance.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountBalance records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountBalance, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountBalance> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountBalance.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountBalance to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountBalance accountBalance = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountBalance)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountBalance SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountBalance accountBalance)
		{
			return accountBalance;
		}
	}
	
	/// <summary>
	/// This class provides the DateOfBirth data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class DateOfBirth : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DateOfBirth, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DateOfBirth> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static DateOfBirth()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DateOfBirth.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DateOfBirth, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DateOfBirth>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DateOfBirth.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DateOfBirth records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DateOfBirth, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DateOfBirth> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DateOfBirth.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DateOfBirth to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DateOfBirth dateOfBirth = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DateOfBirth)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DateOfBirth SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DateOfBirth dateOfBirth)
		{
			return dateOfBirth;
		}
	}
	
	/// <summary>
	/// This class provides the FirstName data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class FirstName : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.FirstName, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.FirstName> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static FirstName()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.FirstName.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.FirstName, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.FirstName>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.FirstName.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.FirstName records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.FirstName, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.FirstName> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.FirstName.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.FirstName to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.FirstName firstName = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.FirstName)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.FirstName SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.FirstName firstName)
		{
			return firstName;
		}
	}
	
	/// <summary>
	/// This class provides the HeatIndex data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class HeatIndex : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.HeatIndex, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.HeatIndex> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static HeatIndex()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.HeatIndex.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.HeatIndex, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.HeatIndex>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.HeatIndex.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.HeatIndex records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.HeatIndex, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.HeatIndex> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.HeatIndex.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.HeatIndex to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.HeatIndex heatIndex = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.HeatIndex)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.HeatIndex SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.HeatIndex heatIndex)
		{
			return heatIndex;
		}
	}
	
	/// <summary>
	/// This class provides the IsEmployed data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class IsEmployed : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsEmployed, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsEmployed> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static IsEmployed()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsEmployed.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsEmployed, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsEmployed>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsEmployed.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsEmployed records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsEmployed, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsEmployed> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsEmployed.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsEmployed to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsEmployed isEmployed = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsEmployed)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsEmployed SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsEmployed isEmployed)
		{
			return isEmployed;
		}
	}
	
	/// <summary>
	/// This class provides the IsRead data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class IsRead : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsRead, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsRead> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static IsRead()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsRead.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsRead, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsRead>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsRead.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsRead records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsRead, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsRead> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsRead.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsRead to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsRead isRead = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsRead)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsRead SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsRead isRead)
		{
			return isRead;
		}
	}
	
	/// <summary>
	/// This class provides the DebtHolderName data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class DebtHolderName : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DebtHolderName, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DebtHolderName> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static DebtHolderName()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DebtHolderName.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DebtHolderName, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DebtHolderName>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DebtHolderName.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DebtHolderName records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DebtHolderName, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DebtHolderName> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DebtHolderName.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DebtHolderName to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DebtHolderName debtHolderName = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DebtHolderName)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DebtHolderName SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DebtHolderName debtHolderName)
		{
			return debtHolderName;
		}
	}
	
	/// <summary>
	/// This class provides the LastName data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class LastName : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.LastName, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.LastName> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static LastName()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.LastName.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.LastName, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.LastName>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.LastName.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.LastName records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.LastName, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.LastName> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.LastName.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.LastName to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.LastName lastName = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.LastName)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.LastName SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.LastName lastName)
		{
			return lastName;
		}
	}
	
	/// <summary>
	/// This class provides the PostalCode data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class PostalCode : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.PostalCode, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.PostalCode> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static PostalCode()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.PostalCode.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.PostalCode, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.PostalCode>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.PostalCode.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.PostalCode records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.PostalCode, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.PostalCode> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.PostalCode.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.PostalCode to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.PostalCode postalCode = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.PostalCode)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.PostalCode SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.PostalCode postalCode)
		{
			return postalCode;
		}
	}
	
	/// <summary>
	/// This class provides the MiddleName data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class MiddleName : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MiddleName, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MiddleName> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static MiddleName()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MiddleName.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MiddleName, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MiddleName>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MiddleName.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MiddleName records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MiddleName, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MiddleName> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MiddleName.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MiddleName to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MiddleName middleName = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MiddleName)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MiddleName SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MiddleName middleName)
		{
			return middleName;
		}
	}
	
	/// <summary>
	/// This class provides the ModifiedBy data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class ModifiedBy : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedBy, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedBy> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static ModifiedBy()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedBy.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedBy, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedBy>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedBy.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedBy records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedBy, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedBy> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedBy.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedBy to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedBy modifiedBy = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedBy)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedBy SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedBy modifiedBy)
		{
			return modifiedBy;
		}
	}
	
	/// <summary>
	/// This class provides the ModifiedDateTime data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class ModifiedDateTime : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedDateTime, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedDateTime> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static ModifiedDateTime()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedDateTime.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedDateTime, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedDateTime>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedDateTime.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedDateTime records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedDateTime, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedDateTime> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedDateTime.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedDateTime to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedDateTime modifiedDateTime = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedDateTime)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedDateTime SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedDateTime modifiedDateTime)
		{
			return modifiedDateTime;
		}
	}
	
	/// <summary>
	/// This class provides the Province data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class Province : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Province, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Province> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static Province()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Province.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Province, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Province>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Province.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Province records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Province, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Province> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Province.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Province to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Province province = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Province)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Province SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Province province)
		{
			return province;
		}
	}
	
	/// <summary>
	/// This class provides the Salutation data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class Salutation : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Salutation, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Salutation> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static Salutation()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Salutation.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Salutation, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Salutation>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Salutation.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Salutation records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Salutation, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Salutation> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Salutation.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Salutation to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Salutation salutation = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Salutation)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Salutation SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Salutation salutation)
		{
			return salutation;
		}
	}
	
	/// <summary>
	/// This class provides the SecurityName data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class SecurityName : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SecurityName, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SecurityName> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static SecurityName()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SecurityName.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SecurityName, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SecurityName>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SecurityName.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SecurityName records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SecurityName, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SecurityName> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SecurityName.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SecurityName to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SecurityName securityName = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SecurityName)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SecurityName SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SecurityName securityName)
		{
			return securityName;
		}
	}
	
	/// <summary>
	/// This class provides the SelectRow data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class SelectRow : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SelectRow, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SelectRow> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static SelectRow()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SelectRow.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SelectRow, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SelectRow>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SelectRow.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SelectRow records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SelectRow, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SelectRow> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SelectRow.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SelectRow to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SelectRow selectRow = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SelectRow)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SelectRow SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SelectRow selectRow)
		{
			return selectRow;
		}
	}
	
	/// <summary>
	/// This class provides the SocialSecurityNumber data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class SocialSecurityNumber : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SocialSecurityNumber, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SocialSecurityNumber> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static SocialSecurityNumber()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SocialSecurityNumber.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SocialSecurityNumber, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SocialSecurityNumber>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SocialSecurityNumber.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SocialSecurityNumber records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SocialSecurityNumber, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SocialSecurityNumber> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SocialSecurityNumber.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SocialSecurityNumber to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SocialSecurityNumber socialSecurityNumber = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SocialSecurityNumber)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SocialSecurityNumber SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SocialSecurityNumber socialSecurityNumber)
		{
			return socialSecurityNumber;
		}
	}
	
	/// <summary>
	/// This class provides the Status data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class Status : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Status, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Status> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static Status()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Status.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Status, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Status>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Status.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Status records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Status, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Status> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Status.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Status to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Status status = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Status)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Status SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Status status)
		{
			return status;
		}
	}
	
	/// <summary>
	/// This class provides the Suffix data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class Suffix : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Suffix, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Suffix> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static Suffix()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Suffix.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Suffix, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Suffix>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Suffix.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Suffix records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Suffix, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Suffix> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Suffix.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Suffix to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Suffix suffix = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Suffix)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Suffix SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Suffix suffix)
		{
			return suffix;
		}
	}
	
	/// <summary>
	/// This class provides the MatchHeader data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class MatchHeader : FluidTrade.Core.IContent
	{
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountBalance accountBalance;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountNumber accountNumber;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address1 address1;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address2 address2;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Blotter blotter;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.City city;
		
		private FluidTrade.Core.ComplexComparer<FluidTrade.Guardian.Schema.DebtHolderMatch.Match> comparer;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedBy createdBy;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedDateTime createdDateTime;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DateOfBirth dateOfBirth;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DebtHolderName debtHolderName;
		
		private FluidTrade.Core.ComplexFilter<FluidTrade.Guardian.Schema.DebtHolderMatch.Match> filter;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.FirstName firstName;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.HeatIndex heatIndex;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsEmployed isEmployed;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsRead isRead;
		
		internal object key;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.LastName lastName;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatch.Match[] matchList;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MiddleName middleName;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedBy modifiedBy;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedDateTime modifiedDateTime;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.PostalCode postalCode;
		
		private FluidTrade.Core.ComplexFilter<FluidTrade.Guardian.MatchRow> prefilter;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Province province;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Salutation salutation;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SecurityName securityName;
		
		private System.Func<FluidTrade.Guardian.MatchRow, FluidTrade.Guardian.Schema.DebtHolderMatch.Match> selector;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SelectRow selectRow;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MatchHeader, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MatchHeader> selectSelf;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SocialSecurityNumber socialSecurityNumber;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Status status;
		
		internal FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Suffix suffix;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static MatchHeader()
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MatchHeader.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MatchHeader, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MatchHeader>(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MatchHeader.SelectFromSelf);
		}
		
		/// <summary>
		/// Creates a FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MatchHeader.
		/// </summary>
		public MatchHeader()
		{
			this.accountNumber = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountNumber();
			this.address1 = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address1();
			this.address2 = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address2();
			this.blotter = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Blotter();
			this.city = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.City();
			this.createdBy = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedBy();
			this.createdDateTime = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedDateTime();
			this.accountBalance = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountBalance();
			this.dateOfBirth = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DateOfBirth();
			this.firstName = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.FirstName();
			this.heatIndex = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.HeatIndex();
			this.isEmployed = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsEmployed();
			this.isRead = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsRead();
			this.debtHolderName = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DebtHolderName();
			this.lastName = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.LastName();
			this.postalCode = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.PostalCode();
			this.middleName = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MiddleName();
			this.modifiedBy = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedBy();
			this.modifiedDateTime = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedDateTime();
			this.province = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Province();
			this.salutation = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Salutation();
			this.securityName = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SecurityName();
			this.selectRow = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SelectRow();
			this.socialSecurityNumber = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SocialSecurityNumber();
			this.status = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Status();
			this.suffix = new FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Suffix();
		}
		
		/// <summary>
		/// AccountBalance
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountBalance AccountBalance
		{
			get
			{
				return this.accountBalance;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// AccountNumber
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.AccountNumber AccountNumber
		{
			get
			{
				return this.accountNumber;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Address1
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address1 Address1
		{
			get
			{
				return this.address1;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Address2
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Address2 Address2
		{
			get
			{
				return this.address2;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Blotter
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Blotter Blotter
		{
			get
			{
				return this.blotter;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// City
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.City City
		{
			get
			{
				return this.city;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the complex comparison for ordering records from the result set.
		/// </summary>
		public FluidTrade.Core.ComplexComparer<FluidTrade.Guardian.Schema.DebtHolderMatch.Match> Comparer
		{
			get
			{
				return this.comparer;
			}
			set
			{
				this.comparer = value;
			}
		}
		
		/// <summary>
		/// CreatedBy
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedBy CreatedBy
		{
			get
			{
				return this.createdBy;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// CreatedDateTime
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.CreatedDateTime CreatedDateTime
		{
			get
			{
				return this.createdDateTime;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// DateOfBirth
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DateOfBirth DateOfBirth
		{
			get
			{
				return this.dateOfBirth;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// DebtHolderName
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.DebtHolderName DebtHolderName
		{
			get
			{
				return this.debtHolderName;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the complex filter used to remove records from the result set.
		/// </summary>
		public FluidTrade.Core.ComplexFilter<FluidTrade.Guardian.Schema.DebtHolderMatch.Match> Filter
		{
			get
			{
				return this.filter;
			}
			set
			{
				this.filter = value;
			}
		}
		
		/// <summary>
		/// FirstName
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.FirstName FirstName
		{
			get
			{
				return this.firstName;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// HeatIndex
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.HeatIndex HeatIndex
		{
			get
			{
				return this.heatIndex;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// IsEmployed
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsEmployed IsEmployed
		{
			get
			{
				return this.isEmployed;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// IsRead
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.IsRead IsRead
		{
			get
			{
				return this.isRead;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// LastName
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.LastName LastName
		{
			get
			{
				return this.lastName;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// MatchList
		/// </summary>
		public System.Collections.Generic.IEnumerable<FluidTrade.Guardian.Schema.DebtHolderMatch.Match> MatchList
		{
			get
			{
				return this.matchList;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// MiddleName
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MiddleName MiddleName
		{
			get
			{
				return this.middleName;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// ModifiedBy
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedBy ModifiedBy
		{
			get
			{
				return this.modifiedBy;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// ModifiedDateTime
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.ModifiedDateTime ModifiedDateTime
		{
			get
			{
				return this.modifiedDateTime;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// PostalCode
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.PostalCode PostalCode
		{
			get
			{
				return this.postalCode;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the complex filter used to remove records from the result set.
		/// </summary>
		public FluidTrade.Core.ComplexFilter<FluidTrade.Guardian.MatchRow> Prefilter
		{
			get
			{
				return this.prefilter;
			}
			set
			{
				this.prefilter = value;
			}
		}
		
		/// <summary>
		/// Province
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Province Province
		{
			get
			{
				return this.province;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Salutation
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Salutation Salutation
		{
			get
			{
				return this.salutation;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// SecurityName
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SecurityName SecurityName
		{
			get
			{
				return this.securityName;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the delegate used to select a destination record from a source.
		/// </summary>
		public System.Func<FluidTrade.Guardian.MatchRow, FluidTrade.Guardian.Schema.DebtHolderMatch.Match> Selector
		{
			get
			{
				return this.selector;
			}
			set
			{
				this.selector = value;
			}
		}
		
		/// <summary>
		/// SelectRow
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SelectRow SelectRow
		{
			get
			{
				return this.selectRow;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MatchHeader records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MatchHeader, FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MatchHeader> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MatchHeader.selectSelf;
			}
		}
		
		/// <summary>
		/// SocialSecurityNumber
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.SocialSecurityNumber SocialSecurityNumber
		{
			get
			{
				return this.socialSecurityNumber;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Status
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Status Status
		{
			get
			{
				return this.status;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Suffix
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.Suffix Suffix
		{
			get
			{
				return this.suffix;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MatchHeader to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MatchHeader matchHeader = ((FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MatchHeader)(iContent));
			this.accountNumber.Copy(matchHeader.accountNumber);
			this.address1.Copy(matchHeader.address1);
			this.address2.Copy(matchHeader.address2);
			this.blotter.Copy(matchHeader.blotter);
			this.city.Copy(matchHeader.city);
			this.createdBy.Copy(matchHeader.createdBy);
			this.createdDateTime.Copy(matchHeader.createdDateTime);
			this.accountBalance.Copy(matchHeader.accountBalance);
			this.dateOfBirth.Copy(matchHeader.dateOfBirth);
			this.firstName.Copy(matchHeader.firstName);
			this.heatIndex.Copy(matchHeader.heatIndex);
			this.isEmployed.Copy(matchHeader.isEmployed);
			this.isRead.Copy(matchHeader.isRead);
			this.debtHolderName.Copy(matchHeader.debtHolderName);
			this.lastName.Copy(matchHeader.lastName);
			this.postalCode.Copy(matchHeader.postalCode);
			this.middleName.Copy(matchHeader.middleName);
			this.modifiedBy.Copy(matchHeader.modifiedBy);
			this.modifiedDateTime.Copy(matchHeader.modifiedDateTime);
			this.province.Copy(matchHeader.province);
			this.salutation.Copy(matchHeader.salutation);
			this.securityName.Copy(matchHeader.securityName);
			this.selectRow.Copy(matchHeader.selectRow);
			this.socialSecurityNumber.Copy(matchHeader.socialSecurityNumber);
			this.status.Copy(matchHeader.status);
			this.suffix.Copy(matchHeader.suffix);
		}
		
		/// <summary>
		/// Creates a FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MatchHeader.
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MatchHeader Select(System.Guid guid)
		{
			this.key = guid;
			System.Collections.Generic.IEnumerable<FluidTrade.Guardian.MatchRow> dde1c665e0f5540cd888a2b4c81863290 = System.Linq.Enumerable.Where<FluidTrade.Guardian.MatchRow>(DataModel.Match, this.prefilter.Filter);
			System.Collections.Generic.IEnumerable<FluidTrade.Guardian.Schema.DebtHolderMatch.Match> g3bd2bdc50a51430faa561bea4eb9a872 = System.Linq.Enumerable.Select<FluidTrade.Guardian.MatchRow, FluidTrade.Guardian.Schema.DebtHolderMatch.Match>(dde1c665e0f5540cd888a2b4c81863290, this.selector);
			System.Collections.Generic.IEnumerable<FluidTrade.Guardian.Schema.DebtHolderMatch.Match> a72d1a3d15de746a3b942d20bc94a4e86 = System.Linq.Enumerable.Where<FluidTrade.Guardian.Schema.DebtHolderMatch.Match>(g3bd2bdc50a51430faa561bea4eb9a872, this.filter.Filter);
			System.Collections.Generic.IEnumerable<FluidTrade.Guardian.Schema.DebtHolderMatch.Match> d6e0e654d115a471cbd0bbed6ffda6b02 = System.Linq.Enumerable.OrderBy<FluidTrade.Guardian.Schema.DebtHolderMatch.Match, FluidTrade.Guardian.Schema.DebtHolderMatch.Match>(a72d1a3d15de746a3b942d20bc94a4e86, FluidTrade.Guardian.Schema.DebtHolderMatch.Match.SelectSelf, this.comparer);
			this.matchList = System.Linq.Enumerable.ToArray(d6e0e654d115a471cbd0bbed6ffda6b02);
			return this;
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MatchHeader SelectFromSelf(FluidTrade.Guardian.Schema.DebtHolderMatchHeader.MatchHeader matchHeader)
		{
			return matchHeader;
		}
	}
}
