//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Windows.Markup.XmlnsDefinitionAttribute("urn:schemas-fluidtrade-com:guardian:debt-negotiator-payment-summary", "FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary")]

namespace FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary
{
	
	
	/// <summary>
	/// This class provides the ActiveFlag data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class ActiveFlag : FluidTrade.Core.IContent, System.ComponentModel.INotifyPropertyChanged
	{
		
		internal bool active;
		
		internal bool isActive;
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActiveFlag, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActiveFlag> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static ActiveFlag()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActiveFlag.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActiveFlag, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActiveFlag>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActiveFlag.SelectFromSelf);
		}
		
		/// <summary>
		/// Active
		/// </summary>
		public bool Active
		{
			get
			{
				return this.active;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// IsActive
		/// </summary>
		public bool IsActive
		{
			get
			{
				return this.isActive;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActiveFlag records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActiveFlag, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActiveFlag> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActiveFlag.selectSelf;
			}
		}
		
		/// <summary>
		/// Indicates that one of the object's properties has changed.
		/// </summary>
		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActiveFlag to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActiveFlag activeFlag = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActiveFlag)(iContent));
			if ((this.isActive != activeFlag.isActive))
			{
				this.isActive = activeFlag.isActive;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("IsActive"));
				}
			}
			if ((this.active != activeFlag.active))
			{
				this.active = activeFlag.active;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Active"));
				}
			}
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActiveFlag SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActiveFlag activeFlag)
		{
			return activeFlag;
		}
	}
	
	/// <summary>
	/// This class provides the ActualPaymentDate data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class ActualPaymentDate : FluidTrade.Core.IContent, System.ComponentModel.INotifyPropertyChanged
	{
		
		internal bool isActive;
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentDate, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentDate> selectSelf;
		
		internal string text;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static ActualPaymentDate()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentDate.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentDate, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentDate>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentDate.SelectFromSelf);
		}
		
		/// <summary>
		/// IsActive
		/// </summary>
		public bool IsActive
		{
			get
			{
				return this.isActive;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentDate records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentDate, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentDate> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentDate.selectSelf;
			}
		}
		
		/// <summary>
		/// Text
		/// </summary>
		public string Text
		{
			get
			{
				return this.text;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Indicates that one of the object's properties has changed.
		/// </summary>
		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentDate to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentDate actualPaymentDate = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentDate)(iContent));
			if ((this.isActive != actualPaymentDate.isActive))
			{
				this.isActive = actualPaymentDate.isActive;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("IsActive"));
				}
			}
			if ((this.text != actualPaymentDate.text))
			{
				this.text = actualPaymentDate.text;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Text"));
				}
			}
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentDate SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentDate actualPaymentDate)
		{
			return actualPaymentDate;
		}
	}
	
	/// <summary>
	/// This class provides the ActualPaymentValue data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class ActualPaymentValue : FluidTrade.Core.IContent, System.ComponentModel.INotifyPropertyChanged
	{
		
		internal bool isActive;
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentValue, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentValue> selectSelf;
		
		internal object text;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static ActualPaymentValue()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentValue.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentValue, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentValue>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentValue.SelectFromSelf);
		}
		
		/// <summary>
		/// IsActive
		/// </summary>
		public bool IsActive
		{
			get
			{
				return this.isActive;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentValue records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentValue, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentValue> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentValue.selectSelf;
			}
		}
		
		/// <summary>
		/// Text
		/// </summary>
		public object Text
		{
			get
			{
				return this.text;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Indicates that one of the object's properties has changed.
		/// </summary>
		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentValue to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentValue actualPaymentValue = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentValue)(iContent));
			if ((this.isActive != actualPaymentValue.isActive))
			{
				this.isActive = actualPaymentValue.isActive;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("IsActive"));
				}
			}
			if ((this.text != actualPaymentValue.text))
			{
				this.text = actualPaymentValue.text;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Text"));
				}
			}
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentValue SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentValue actualPaymentValue)
		{
			return actualPaymentValue;
		}
	}
	
	/// <summary>
	/// This class provides the CheckId data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class CheckId : FluidTrade.Core.IContent, System.ComponentModel.INotifyPropertyChanged
	{
		
		internal bool isActive;
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CheckId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CheckId> selectSelf;
		
		internal object text;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static CheckId()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CheckId.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CheckId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CheckId>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CheckId.SelectFromSelf);
		}
		
		/// <summary>
		/// IsActive
		/// </summary>
		public bool IsActive
		{
			get
			{
				return this.isActive;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CheckId records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CheckId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CheckId> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CheckId.selectSelf;
			}
		}
		
		/// <summary>
		/// Text
		/// </summary>
		public object Text
		{
			get
			{
				return this.text;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Indicates that one of the object's properties has changed.
		/// </summary>
		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CheckId to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CheckId checkId = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CheckId)(iContent));
			if ((this.isActive != checkId.isActive))
			{
				this.isActive = checkId.isActive;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("IsActive"));
				}
			}
			if ((this.text != checkId.text))
			{
				this.text = checkId.text;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Text"));
				}
			}
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CheckId SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CheckId checkId)
		{
			return checkId;
		}
	}
	
	/// <summary>
	/// This class provides the ClearedDate data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class ClearedDate : FluidTrade.Core.IContent, System.ComponentModel.INotifyPropertyChanged
	{
		
		internal bool isActive;
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ClearedDate, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ClearedDate> selectSelf;
		
		internal object text;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static ClearedDate()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ClearedDate.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ClearedDate, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ClearedDate>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ClearedDate.SelectFromSelf);
		}
		
		/// <summary>
		/// IsActive
		/// </summary>
		public bool IsActive
		{
			get
			{
				return this.isActive;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ClearedDate records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ClearedDate, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ClearedDate> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ClearedDate.selectSelf;
			}
		}
		
		/// <summary>
		/// Text
		/// </summary>
		public object Text
		{
			get
			{
				return this.text;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Indicates that one of the object's properties has changed.
		/// </summary>
		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ClearedDate to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ClearedDate clearedDate = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ClearedDate)(iContent));
			if ((this.isActive != clearedDate.isActive))
			{
				this.isActive = clearedDate.isActive;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("IsActive"));
				}
			}
			if ((this.text != clearedDate.text))
			{
				this.text = clearedDate.text;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Text"));
				}
			}
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ClearedDate SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ClearedDate clearedDate)
		{
			return clearedDate;
		}
	}
	
	/// <summary>
	/// This class provides the CreatedDateTime data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class CreatedDateTime : FluidTrade.Core.IContent, System.ComponentModel.INotifyPropertyChanged
	{
		
		internal bool isActive;
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedDateTime, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedDateTime> selectSelf;
		
		internal object text;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static CreatedDateTime()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedDateTime.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedDateTime, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedDateTime>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedDateTime.SelectFromSelf);
		}
		
		/// <summary>
		/// IsActive
		/// </summary>
		public bool IsActive
		{
			get
			{
				return this.isActive;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedDateTime records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedDateTime, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedDateTime> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedDateTime.selectSelf;
			}
		}
		
		/// <summary>
		/// Text
		/// </summary>
		public object Text
		{
			get
			{
				return this.text;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Indicates that one of the object's properties has changed.
		/// </summary>
		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedDateTime to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedDateTime createdDateTime = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedDateTime)(iContent));
			if ((this.isActive != createdDateTime.isActive))
			{
				this.isActive = createdDateTime.isActive;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("IsActive"));
				}
			}
			if ((this.text != createdDateTime.text))
			{
				this.text = createdDateTime.text;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Text"));
				}
			}
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedDateTime SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedDateTime createdDateTime)
		{
			return createdDateTime;
		}
	}
	
	/// <summary>
	/// This class provides the CreatedUserId data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class CreatedUserId : FluidTrade.Core.IContent, System.ComponentModel.INotifyPropertyChanged
	{
		
		internal bool isActive;
		
		internal object key;
		
		internal string name;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedUserId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedUserId> selectSelf;
		
		internal object text;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static CreatedUserId()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedUserId.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedUserId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedUserId>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedUserId.SelectFromSelf);
		}
		
		/// <summary>
		/// IsActive
		/// </summary>
		public bool IsActive
		{
			get
			{
				return this.isActive;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Name
		/// </summary>
		public string Name
		{
			get
			{
				return this.name;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedUserId records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedUserId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedUserId> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedUserId.selectSelf;
			}
		}
		
		/// <summary>
		/// Text
		/// </summary>
		public object Text
		{
			get
			{
				return this.text;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Indicates that one of the object's properties has changed.
		/// </summary>
		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedUserId to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedUserId createdUserId = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedUserId)(iContent));
			if ((this.isActive != createdUserId.isActive))
			{
				this.isActive = createdUserId.isActive;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("IsActive"));
				}
			}
			if ((this.text != createdUserId.text))
			{
				this.text = createdUserId.text;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Text"));
				}
			}
			if ((this.name != createdUserId.name))
			{
				this.name = createdUserId.name;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Name"));
				}
			}
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedUserId SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedUserId createdUserId)
		{
			return createdUserId;
		}
	}
	
	/// <summary>
	/// This class provides the EffectivePaymentDate data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class EffectivePaymentDate : FluidTrade.Core.IContent, System.ComponentModel.INotifyPropertyChanged
	{
		
		internal bool isActive;
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentDate, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentDate> selectSelf;
		
		internal object text;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static EffectivePaymentDate()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentDate.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentDate, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentDate>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentDate.SelectFromSelf);
		}
		
		/// <summary>
		/// IsActive
		/// </summary>
		public bool IsActive
		{
			get
			{
				return this.isActive;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentDate records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentDate, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentDate> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentDate.selectSelf;
			}
		}
		
		/// <summary>
		/// Text
		/// </summary>
		public object Text
		{
			get
			{
				return this.text;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Indicates that one of the object's properties has changed.
		/// </summary>
		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentDate to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentDate effectivePaymentDate = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentDate)(iContent));
			if ((this.isActive != effectivePaymentDate.isActive))
			{
				this.isActive = effectivePaymentDate.isActive;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("IsActive"));
				}
			}
			if ((this.text != effectivePaymentDate.text))
			{
				this.text = effectivePaymentDate.text;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Text"));
				}
			}
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentDate SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentDate effectivePaymentDate)
		{
			return effectivePaymentDate;
		}
	}
	
	/// <summary>
	/// This class provides the EffectivePaymentValue data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class EffectivePaymentValue : FluidTrade.Core.IContent, System.ComponentModel.INotifyPropertyChanged
	{
		
		internal bool isActive;
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentValue, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentValue> selectSelf;
		
		internal object text;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static EffectivePaymentValue()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentValue.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentValue, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentValue>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentValue.SelectFromSelf);
		}
		
		/// <summary>
		/// IsActive
		/// </summary>
		public bool IsActive
		{
			get
			{
				return this.isActive;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentValue records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentValue, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentValue> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentValue.selectSelf;
			}
		}
		
		/// <summary>
		/// Text
		/// </summary>
		public object Text
		{
			get
			{
				return this.text;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Indicates that one of the object's properties has changed.
		/// </summary>
		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentValue to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentValue effectivePaymentValue = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentValue)(iContent));
			if ((this.isActive != effectivePaymentValue.isActive))
			{
				this.isActive = effectivePaymentValue.isActive;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("IsActive"));
				}
			}
			if ((this.text != effectivePaymentValue.text))
			{
				this.text = effectivePaymentValue.text;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Text"));
				}
			}
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentValue SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentValue effectivePaymentValue)
		{
			return effectivePaymentValue;
		}
	}
	
	/// <summary>
	/// This class provides the Fee0 data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class Fee0 : FluidTrade.Core.IContent, System.ComponentModel.INotifyPropertyChanged
	{
		
		internal bool isActive;
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Fee0, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Fee0> selectSelf;
		
		internal object text;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static Fee0()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Fee0.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Fee0, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Fee0>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Fee0.SelectFromSelf);
		}
		
		/// <summary>
		/// IsActive
		/// </summary>
		public bool IsActive
		{
			get
			{
				return this.isActive;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Fee0 records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Fee0, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Fee0> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Fee0.selectSelf;
			}
		}
		
		/// <summary>
		/// Text
		/// </summary>
		public object Text
		{
			get
			{
				return this.text;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Indicates that one of the object's properties has changed.
		/// </summary>
		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Fee0 to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Fee0 fee0 = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Fee0)(iContent));
			if ((this.isActive != fee0.isActive))
			{
				this.isActive = fee0.isActive;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("IsActive"));
				}
			}
			if ((this.text != fee0.text))
			{
				this.text = fee0.text;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Text"));
				}
			}
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Fee0 SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Fee0 fee0)
		{
			return fee0;
		}
	}
	
	/// <summary>
	/// This class provides the IsCleared data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class IsCleared : FluidTrade.Core.IContent, System.ComponentModel.INotifyPropertyChanged
	{
		
		internal bool cleared;
		
		internal bool isActive;
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.IsCleared, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.IsCleared> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static IsCleared()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.IsCleared.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.IsCleared, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.IsCleared>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.IsCleared.SelectFromSelf);
		}
		
		/// <summary>
		/// Cleared
		/// </summary>
		public bool Cleared
		{
			get
			{
				return this.cleared;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// IsActive
		/// </summary>
		public bool IsActive
		{
			get
			{
				return this.isActive;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.IsCleared records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.IsCleared, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.IsCleared> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.IsCleared.selectSelf;
			}
		}
		
		/// <summary>
		/// Indicates that one of the object's properties has changed.
		/// </summary>
		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.IsCleared to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.IsCleared isCleared = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.IsCleared)(iContent));
			if ((this.isActive != isCleared.isActive))
			{
				this.isActive = isCleared.isActive;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("IsActive"));
				}
			}
			if ((this.cleared != isCleared.cleared))
			{
				this.cleared = isCleared.cleared;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Cleared"));
				}
			}
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.IsCleared SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.IsCleared isCleared)
		{
			return isCleared;
		}
	}
	
	/// <summary>
	/// This class provides the Memo0 data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class Memo0 : FluidTrade.Core.IContent, System.ComponentModel.INotifyPropertyChanged
	{
		
		internal bool isActive;
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo0, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo0> selectSelf;
		
		internal object text;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static Memo0()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo0.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo0, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo0>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo0.SelectFromSelf);
		}
		
		/// <summary>
		/// IsActive
		/// </summary>
		public bool IsActive
		{
			get
			{
				return this.isActive;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo0 records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo0, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo0> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo0.selectSelf;
			}
		}
		
		/// <summary>
		/// Text
		/// </summary>
		public object Text
		{
			get
			{
				return this.text;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Indicates that one of the object's properties has changed.
		/// </summary>
		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo0 to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo0 memo0 = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo0)(iContent));
			if ((this.isActive != memo0.isActive))
			{
				this.isActive = memo0.isActive;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("IsActive"));
				}
			}
			if ((this.text != memo0.text))
			{
				this.text = memo0.text;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Text"));
				}
			}
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo0 SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo0 memo0)
		{
			return memo0;
		}
	}
	
	/// <summary>
	/// This class provides the Memo1 data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class Memo1 : FluidTrade.Core.IContent, System.ComponentModel.INotifyPropertyChanged
	{
		
		internal bool isActive;
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo1, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo1> selectSelf;
		
		internal object text;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static Memo1()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo1.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo1, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo1>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo1.SelectFromSelf);
		}
		
		/// <summary>
		/// IsActive
		/// </summary>
		public bool IsActive
		{
			get
			{
				return this.isActive;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo1 records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo1, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo1> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo1.selectSelf;
			}
		}
		
		/// <summary>
		/// Text
		/// </summary>
		public object Text
		{
			get
			{
				return this.text;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Indicates that one of the object's properties has changed.
		/// </summary>
		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo1 to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo1 memo1 = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo1)(iContent));
			if ((this.isActive != memo1.isActive))
			{
				this.isActive = memo1.isActive;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("IsActive"));
				}
			}
			if ((this.text != memo1.text))
			{
				this.text = memo1.text;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Text"));
				}
			}
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo1 SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo1 memo1)
		{
			return memo1;
		}
	}
	
	/// <summary>
	/// This class provides the Memo2 data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class Memo2 : FluidTrade.Core.IContent, System.ComponentModel.INotifyPropertyChanged
	{
		
		internal bool isActive;
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo2, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo2> selectSelf;
		
		internal object text;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static Memo2()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo2.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo2, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo2>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo2.SelectFromSelf);
		}
		
		/// <summary>
		/// IsActive
		/// </summary>
		public bool IsActive
		{
			get
			{
				return this.isActive;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo2 records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo2, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo2> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo2.selectSelf;
			}
		}
		
		/// <summary>
		/// Text
		/// </summary>
		public object Text
		{
			get
			{
				return this.text;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Indicates that one of the object's properties has changed.
		/// </summary>
		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo2 to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo2 memo2 = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo2)(iContent));
			if ((this.isActive != memo2.isActive))
			{
				this.isActive = memo2.isActive;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("IsActive"));
				}
			}
			if ((this.text != memo2.text))
			{
				this.text = memo2.text;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Text"));
				}
			}
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo2 SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo2 memo2)
		{
			return memo2;
		}
	}
	
	/// <summary>
	/// This class provides the ModifiedDateTime data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class ModifiedDateTime : FluidTrade.Core.IContent, System.ComponentModel.INotifyPropertyChanged
	{
		
		internal bool isActive;
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedDateTime, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedDateTime> selectSelf;
		
		internal object text;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static ModifiedDateTime()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedDateTime.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedDateTime, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedDateTime>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedDateTime.SelectFromSelf);
		}
		
		/// <summary>
		/// IsActive
		/// </summary>
		public bool IsActive
		{
			get
			{
				return this.isActive;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedDateTime records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedDateTime, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedDateTime> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedDateTime.selectSelf;
			}
		}
		
		/// <summary>
		/// Text
		/// </summary>
		public object Text
		{
			get
			{
				return this.text;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Indicates that one of the object's properties has changed.
		/// </summary>
		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedDateTime to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedDateTime modifiedDateTime = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedDateTime)(iContent));
			if ((this.isActive != modifiedDateTime.isActive))
			{
				this.isActive = modifiedDateTime.isActive;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("IsActive"));
				}
			}
			if ((this.text != modifiedDateTime.text))
			{
				this.text = modifiedDateTime.text;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Text"));
				}
			}
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedDateTime SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedDateTime modifiedDateTime)
		{
			return modifiedDateTime;
		}
	}
	
	/// <summary>
	/// This class provides the ModifiedUserId data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class ModifiedUserId : FluidTrade.Core.IContent, System.ComponentModel.INotifyPropertyChanged
	{
		
		internal bool isActive;
		
		internal object key;
		
		internal string name;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedUserId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedUserId> selectSelf;
		
		internal object text;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static ModifiedUserId()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedUserId.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedUserId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedUserId>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedUserId.SelectFromSelf);
		}
		
		/// <summary>
		/// IsActive
		/// </summary>
		public bool IsActive
		{
			get
			{
				return this.isActive;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Name
		/// </summary>
		public string Name
		{
			get
			{
				return this.name;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedUserId records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedUserId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedUserId> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedUserId.selectSelf;
			}
		}
		
		/// <summary>
		/// Text
		/// </summary>
		public object Text
		{
			get
			{
				return this.text;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Indicates that one of the object's properties has changed.
		/// </summary>
		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedUserId to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedUserId modifiedUserId = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedUserId)(iContent));
			if ((this.isActive != modifiedUserId.isActive))
			{
				this.isActive = modifiedUserId.isActive;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("IsActive"));
				}
			}
			if ((this.name != modifiedUserId.name))
			{
				this.name = modifiedUserId.name;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Name"));
				}
			}
			if ((this.text != modifiedUserId.text))
			{
				this.text = modifiedUserId.text;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Text"));
				}
			}
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedUserId SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedUserId modifiedUserId)
		{
			return modifiedUserId;
		}
	}
	
	/// <summary>
	/// This class provides the SelectRow data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class SelectRow : FluidTrade.Core.IContent, System.ComponentModel.INotifyPropertyChanged
	{
		
		internal bool isActive;
		
		internal object key;
		
		internal string name;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.SelectRow, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.SelectRow> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static SelectRow()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.SelectRow.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.SelectRow, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.SelectRow>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.SelectRow.SelectFromSelf);
		}
		
		/// <summary>
		/// IsActive
		/// </summary>
		public bool IsActive
		{
			get
			{
				return this.isActive;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Name
		/// </summary>
		public string Name
		{
			get
			{
				return this.name;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.SelectRow records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.SelectRow, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.SelectRow> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.SelectRow.selectSelf;
			}
		}
		
		/// <summary>
		/// Indicates that one of the object's properties has changed.
		/// </summary>
		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.SelectRow to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.SelectRow selectRow = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.SelectRow)(iContent));
			if ((this.isActive != selectRow.isActive))
			{
				this.isActive = selectRow.isActive;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("IsActive"));
				}
			}
			if ((this.name != selectRow.name))
			{
				this.name = selectRow.name;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Name"));
				}
			}
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.SelectRow SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.SelectRow selectRow)
		{
			return selectRow;
		}
	}
	
	/// <summary>
	/// This class provides the StatusId data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class StatusId : FluidTrade.Core.IContent, System.ComponentModel.INotifyPropertyChanged
	{
		
		internal bool isActive;
		
		internal object key;
		
		internal string mnemonic;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.StatusId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.StatusId> selectSelf;
		
		internal FluidTrade.Guardian.Status statusCode;
		
		internal object statusIdEnum;
		
		internal string statusSortOrder;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static StatusId()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.StatusId.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.StatusId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.StatusId>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.StatusId.SelectFromSelf);
		}
		
		/// <summary>
		/// IsActive
		/// </summary>
		public bool IsActive
		{
			get
			{
				return this.isActive;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Mnemonic
		/// </summary>
		public string Mnemonic
		{
			get
			{
				return this.mnemonic;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.StatusId records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.StatusId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.StatusId> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.StatusId.selectSelf;
			}
		}
		
		/// <summary>
		/// StatusCode
		/// </summary>
		public FluidTrade.Guardian.Status StatusCode
		{
			get
			{
				return this.statusCode;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// StatusIdEnum
		/// </summary>
		public object StatusIdEnum
		{
			get
			{
				return this.statusIdEnum;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// StatusSortOrder
		/// </summary>
		public string StatusSortOrder
		{
			get
			{
				return this.statusSortOrder;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Indicates that one of the object's properties has changed.
		/// </summary>
		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.StatusId to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.StatusId statusId = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.StatusId)(iContent));
			if ((this.isActive != statusId.isActive))
			{
				this.isActive = statusId.isActive;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("IsActive"));
				}
			}
			if ((this.statusIdEnum != statusId.statusIdEnum))
			{
				this.statusIdEnum = statusId.statusIdEnum;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("StatusIdEnum"));
				}
			}
			if ((this.mnemonic != statusId.mnemonic))
			{
				this.mnemonic = statusId.mnemonic;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Mnemonic"));
				}
			}
			if ((this.statusSortOrder != statusId.statusSortOrder))
			{
				this.statusSortOrder = statusId.statusSortOrder;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("StatusSortOrder"));
				}
			}
			if ((this.statusCode != statusId.statusCode))
			{
				this.statusCode = statusId.statusCode;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("StatusCode"));
				}
			}
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.StatusId SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.StatusId statusId)
		{
			return statusId;
		}
	}
	
	/// <summary>
	/// This class provides the TrackingNumber data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class TrackingNumber : FluidTrade.Core.IContent, System.ComponentModel.INotifyPropertyChanged
	{
		
		internal bool isActive;
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.TrackingNumber, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.TrackingNumber> selectSelf;
		
		internal object text;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static TrackingNumber()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.TrackingNumber.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.TrackingNumber, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.TrackingNumber>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.TrackingNumber.SelectFromSelf);
		}
		
		/// <summary>
		/// IsActive
		/// </summary>
		public bool IsActive
		{
			get
			{
				return this.isActive;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.TrackingNumber records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.TrackingNumber, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.TrackingNumber> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.TrackingNumber.selectSelf;
			}
		}
		
		/// <summary>
		/// Text
		/// </summary>
		public object Text
		{
			get
			{
				return this.text;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Indicates that one of the object's properties has changed.
		/// </summary>
		public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.TrackingNumber to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.TrackingNumber trackingNumber = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.TrackingNumber)(iContent));
			if ((this.isActive != trackingNumber.isActive))
			{
				this.isActive = trackingNumber.isActive;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("IsActive"));
				}
			}
			if ((this.text != trackingNumber.text))
			{
				this.text = trackingNumber.text;
				if ((this.PropertyChanged != null))
				{
					this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs("Text"));
				}
			}
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.TrackingNumber SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.TrackingNumber trackingNumber)
		{
			return trackingNumber;
		}
	}
	
	/// <summary>
	/// This class provides the PaymentSummary data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class PaymentSummary : FluidTrade.Core.IContent
	{
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActiveFlag activeFlag;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentDate actualPaymentDate;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentValue actualPaymentValue;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CheckId checkId;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ClearedDate clearedDate;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedDateTime createdDateTime;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedUserId createdUserId;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentDate effectivePaymentDate;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentValue effectivePaymentValue;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Fee0 fee0;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.IsCleared isCleared;
		
		internal object key;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo0 memo0;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo1 memo1;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo2 memo2;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedDateTime modifiedDateTime;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedUserId modifiedUserId;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.SelectRow selectRow;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary> selectSelf;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.StatusId statusId;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.TrackingNumber trackingNumber;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static PaymentSummary()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary.SelectFromSelf);
		}
		
		/// <summary>
		/// Creates a FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary.
		/// </summary>
		public PaymentSummary()
		{
			this.activeFlag = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActiveFlag();
			this.actualPaymentDate = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentDate();
			this.actualPaymentValue = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentValue();
			this.checkId = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CheckId();
			this.clearedDate = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ClearedDate();
			this.createdDateTime = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedDateTime();
			this.createdUserId = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedUserId();
			this.effectivePaymentDate = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentDate();
			this.effectivePaymentValue = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentValue();
			this.fee0 = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Fee0();
			this.isCleared = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.IsCleared();
			this.memo0 = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo0();
			this.memo1 = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo1();
			this.memo2 = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo2();
			this.modifiedDateTime = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedDateTime();
			this.modifiedUserId = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedUserId();
			this.selectRow = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.SelectRow();
			this.statusId = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.StatusId();
			this.trackingNumber = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.TrackingNumber();
		}
		
		/// <summary>
		/// ActiveFlag
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActiveFlag ActiveFlag
		{
			get
			{
				return this.activeFlag;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// ActualPaymentDate
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentDate ActualPaymentDate
		{
			get
			{
				return this.actualPaymentDate;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// ActualPaymentValue
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ActualPaymentValue ActualPaymentValue
		{
			get
			{
				return this.actualPaymentValue;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// CheckId
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CheckId CheckId
		{
			get
			{
				return this.checkId;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// ClearedDate
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ClearedDate ClearedDate
		{
			get
			{
				return this.clearedDate;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// CreatedDateTime
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedDateTime CreatedDateTime
		{
			get
			{
				return this.createdDateTime;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// CreatedUserId
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.CreatedUserId CreatedUserId
		{
			get
			{
				return this.createdUserId;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// EffectivePaymentDate
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentDate EffectivePaymentDate
		{
			get
			{
				return this.effectivePaymentDate;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// EffectivePaymentValue
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.EffectivePaymentValue EffectivePaymentValue
		{
			get
			{
				return this.effectivePaymentValue;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Fee0
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Fee0 Fee0
		{
			get
			{
				return this.fee0;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// IsCleared
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.IsCleared IsCleared
		{
			get
			{
				return this.isCleared;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Memo0
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo0 Memo0
		{
			get
			{
				return this.memo0;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Memo1
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo1 Memo1
		{
			get
			{
				return this.memo1;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Memo2
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.Memo2 Memo2
		{
			get
			{
				return this.memo2;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// ModifiedDateTime
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedDateTime ModifiedDateTime
		{
			get
			{
				return this.modifiedDateTime;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// ModifiedUserId
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.ModifiedUserId ModifiedUserId
		{
			get
			{
				return this.modifiedUserId;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// SelectRow
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.SelectRow SelectRow
		{
			get
			{
				return this.selectRow;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary.selectSelf;
			}
		}
		
		/// <summary>
		/// StatusId
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.StatusId StatusId
		{
			get
			{
				return this.statusId;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// TrackingNumber
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.TrackingNumber TrackingNumber
		{
			get
			{
				return this.trackingNumber;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary paymentSummary = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary)(iContent));
			this.activeFlag.Copy(paymentSummary.activeFlag);
			this.actualPaymentDate.Copy(paymentSummary.actualPaymentDate);
			this.actualPaymentValue.Copy(paymentSummary.actualPaymentValue);
			this.checkId.Copy(paymentSummary.checkId);
			this.clearedDate.Copy(paymentSummary.clearedDate);
			this.createdDateTime.Copy(paymentSummary.createdDateTime);
			this.createdUserId.Copy(paymentSummary.createdUserId);
			this.effectivePaymentDate.Copy(paymentSummary.effectivePaymentDate);
			this.effectivePaymentValue.Copy(paymentSummary.effectivePaymentValue);
			this.fee0.Copy(paymentSummary.fee0);
			this.isCleared.Copy(paymentSummary.isCleared);
			this.memo0.Copy(paymentSummary.memo0);
			this.memo1.Copy(paymentSummary.memo1);
			this.memo2.Copy(paymentSummary.memo2);
			this.modifiedDateTime.Copy(paymentSummary.modifiedDateTime);
			this.modifiedUserId.Copy(paymentSummary.modifiedUserId);
			this.selectRow.Copy(paymentSummary.selectRow);
			this.statusId.Copy(paymentSummary.statusId);
			this.trackingNumber.Copy(paymentSummary.trackingNumber);
		}
		
		/// <summary>
		/// Creates a FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary.
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary Select(FluidTrade.Guardian.ConsumerTrustPaymentRow paymentRow)
		{
			this.key = paymentRow;
			this.activeFlag.key = new FluidTrade.Core.DataTableCoordinate(paymentRow, DataModel.ConsumerTrustPayment.IsActiveColumn);
			this.activeFlag.isActive = !paymentRow.IsActive;
			this.actualPaymentDate.isActive = !paymentRow.IsActive;
			this.actualPaymentDate.key = new FluidTrade.Core.DataTableCoordinate(paymentRow, DataModel.ConsumerTrustPayment.ActualPaymentDateColumn);
			this.actualPaymentDate.text = paymentRow.IsActualPaymentDateNull() ? "" : paymentRow.ActualPaymentDate.ToString("d");
			this.actualPaymentValue.isActive = !paymentRow.IsActive;
			this.actualPaymentValue.key = new FluidTrade.Core.DataTableCoordinate(paymentRow, DataModel.ConsumerTrustPayment.ActualPaymentValueColumn);
			this.actualPaymentValue.text = paymentRow.IsActualPaymentValueNull() ? 0.0m :paymentRow.ActualPaymentValue;
			this.checkId.isActive = !paymentRow.IsActive;
			this.checkId.key = new FluidTrade.Core.DataTableCoordinate(paymentRow, DataModel.ConsumerTrustPayment.CheckIdColumn);
			this.checkId.text = paymentRow.IsCheckIdNull() ? "" : paymentRow.CheckId;
			this.clearedDate.isActive = !paymentRow.IsActive;
			this.clearedDate.key = new FluidTrade.Core.DataTableCoordinate(paymentRow, DataModel.ConsumerTrustPayment.ClearedDateColumn);
			this.clearedDate.text = paymentRow.ClearedDate;
			this.createdDateTime.isActive = !paymentRow.IsActive;
			this.createdDateTime.key = new FluidTrade.Core.DataTableCoordinate(paymentRow, DataModel.ConsumerTrustPayment.CreatedTimeColumn);
			this.createdDateTime.text = paymentRow.CreatedTime.ToLocalTime();
			this.createdUserId.isActive = !paymentRow.IsActive;
			this.createdUserId.key = new FluidTrade.Core.DataTableCoordinate(paymentRow, DataModel.ConsumerTrustPayment.CreatedUserIdColumn);
			this.createdUserId.name = DataModel.Entity.EntityKey.Find(paymentRow.CreatedUserId).Name;
			this.createdUserId.text = paymentRow.CreatedUserId;
			this.effectivePaymentDate.isActive = !paymentRow.IsActive;
			this.effectivePaymentDate.text = paymentRow.EffectivePaymentDate.ToLocalTime();
			this.effectivePaymentValue.isActive = !paymentRow.IsActive;
			this.effectivePaymentValue.text = paymentRow.EffectivePaymentValue;
			this.fee0.isActive = !paymentRow.IsActive;
			this.fee0.text = paymentRow.IsFee0Null() ? 0.0m : paymentRow.Fee0;
			this.isCleared.isActive = !paymentRow.IsActive;
			this.isCleared.key = new FluidTrade.Core.DataTableCoordinate(paymentRow, DataModel.ConsumerTrustPayment.IsClearedColumn);
			this.isCleared.cleared = paymentRow.IsCleared;
			this.memo0.isActive = !paymentRow.IsActive;
			this.memo0.key = new FluidTrade.Core.DataTableCoordinate(paymentRow, DataModel.ConsumerTrustPayment.Memo0Column);
			this.memo0.text = paymentRow.IsMemo0Null() ? "" : paymentRow.Memo0;
			this.memo1.isActive = !paymentRow.IsActive;
			this.memo1.key = new FluidTrade.Core.DataTableCoordinate(paymentRow, DataModel.ConsumerTrustPayment.Memo1Column);
			this.memo1.text = paymentRow.IsMemo1Null() ? "" : paymentRow.Memo1;
			this.memo2.isActive = !paymentRow.IsActive;
			this.memo2.key = new FluidTrade.Core.DataTableCoordinate(paymentRow, DataModel.ConsumerTrustPayment.Memo2Column);
			this.memo2.text = paymentRow.IsMemo2Null() ? "" : paymentRow.Memo2;
			this.modifiedDateTime.isActive = !paymentRow.IsActive;
			this.modifiedDateTime.key = new FluidTrade.Core.DataTableCoordinate(paymentRow, DataModel.ConsumerTrustPayment.ModifiedTimeColumn);
			this.modifiedDateTime.text = paymentRow.ModifiedTime.ToLocalTime();
			this.modifiedUserId.isActive = !paymentRow.IsActive;
			this.modifiedUserId.key = new FluidTrade.Core.DataTableCoordinate(paymentRow, DataModel.ConsumerTrustPayment.ModifiedUserIdColumn);
			this.modifiedUserId.name = DataModel.Entity.EntityKey.Find(paymentRow.ModifiedUserId).Name;
			this.modifiedUserId.text = paymentRow.ModifiedUserId;
			this.selectRow.isActive = !paymentRow.IsActive;
			this.statusId.isActive = !paymentRow.IsActive;
			this.statusId.key = new FluidTrade.Core.DataTableCoordinate(paymentRow, DataModel.ConsumerTrustPayment.StatusIdColumn);
			this.statusId.mnemonic = paymentRow.StatusRow.Mnemonic;
			this.statusId.statusSortOrder = paymentRow.StatusRow.SortOrder.ToString();
			this.statusId.statusCode = paymentRow.StatusRow.StatusCode;
			this.statusId.statusIdEnum = paymentRow.StatusId;
			this.trackingNumber.isActive = !paymentRow.IsActive;
			this.trackingNumber.key = new FluidTrade.Core.DataTableCoordinate(paymentRow, DataModel.ConsumerTrustPayment.TrackingNumberColumn);
			this.trackingNumber.text = paymentRow.IsTrackingNumberNull() ? "" : paymentRow.TrackingNumber;
			return this;
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary paymentSummary)
		{
			return paymentSummary;
		}
	}
}
