//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Windows.Markup.XmlnsDefinitionAttribute("urn:schemas-fluidtrade-com:guardian:debt-negotiator-payment-summary-header", "FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader")]

namespace FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader
{
	
	
	/// <summary>
	/// This class provides the ActiveFlag data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class ActiveFlag : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActiveFlag, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActiveFlag> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static ActiveFlag()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActiveFlag.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActiveFlag, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActiveFlag>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActiveFlag.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActiveFlag records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActiveFlag, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActiveFlag> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActiveFlag.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActiveFlag to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActiveFlag activeFlag = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActiveFlag)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActiveFlag SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActiveFlag activeFlag)
		{
			return activeFlag;
		}
	}
	
	/// <summary>
	/// This class provides the ActualPaymentDate data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class ActualPaymentDate : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentDate, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentDate> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static ActualPaymentDate()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentDate.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentDate, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentDate>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentDate.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentDate records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentDate, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentDate> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentDate.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentDate to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentDate actualPaymentDate = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentDate)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentDate SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentDate actualPaymentDate)
		{
			return actualPaymentDate;
		}
	}
	
	/// <summary>
	/// This class provides the ActualPaymentValue data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class ActualPaymentValue : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentValue, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentValue> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static ActualPaymentValue()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentValue.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentValue, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentValue>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentValue.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentValue records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentValue, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentValue> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentValue.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentValue to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentValue actualPaymentValue = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentValue)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentValue SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentValue actualPaymentValue)
		{
			return actualPaymentValue;
		}
	}
	
	/// <summary>
	/// This class provides the CheckId data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class CheckId : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CheckId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CheckId> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static CheckId()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CheckId.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CheckId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CheckId>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CheckId.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CheckId records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CheckId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CheckId> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CheckId.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CheckId to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CheckId checkId = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CheckId)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CheckId SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CheckId checkId)
		{
			return checkId;
		}
	}
	
	/// <summary>
	/// This class provides the ClearedDate data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class ClearedDate : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ClearedDate, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ClearedDate> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static ClearedDate()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ClearedDate.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ClearedDate, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ClearedDate>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ClearedDate.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ClearedDate records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ClearedDate, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ClearedDate> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ClearedDate.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ClearedDate to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ClearedDate clearedDate = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ClearedDate)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ClearedDate SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ClearedDate clearedDate)
		{
			return clearedDate;
		}
	}
	
	/// <summary>
	/// This class provides the CreatedDateTime data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class CreatedDateTime : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedDateTime, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedDateTime> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static CreatedDateTime()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedDateTime.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedDateTime, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedDateTime>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedDateTime.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedDateTime records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedDateTime, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedDateTime> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedDateTime.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedDateTime to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedDateTime createdDateTime = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedDateTime)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedDateTime SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedDateTime createdDateTime)
		{
			return createdDateTime;
		}
	}
	
	/// <summary>
	/// This class provides the CreatedUserId data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class CreatedUserId : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedUserId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedUserId> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static CreatedUserId()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedUserId.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedUserId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedUserId>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedUserId.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedUserId records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedUserId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedUserId> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedUserId.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedUserId to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedUserId createdUserId = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedUserId)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedUserId SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedUserId createdUserId)
		{
			return createdUserId;
		}
	}
	
	/// <summary>
	/// This class provides the EffectivePaymentDate data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class EffectivePaymentDate : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentDate, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentDate> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static EffectivePaymentDate()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentDate.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentDate, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentDate>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentDate.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentDate records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentDate, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentDate> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentDate.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentDate to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentDate effectivePaymentDate = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentDate)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentDate SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentDate effectivePaymentDate)
		{
			return effectivePaymentDate;
		}
	}
	
	/// <summary>
	/// This class provides the EffectivePaymentValue data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class EffectivePaymentValue : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentValue, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentValue> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static EffectivePaymentValue()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentValue.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentValue, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentValue>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentValue.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentValue records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentValue, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentValue> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentValue.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentValue to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentValue effectivePaymentValue = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentValue)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentValue SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentValue effectivePaymentValue)
		{
			return effectivePaymentValue;
		}
	}
	
	/// <summary>
	/// This class provides the Fee0 data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class Fee0 : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Fee0, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Fee0> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static Fee0()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Fee0.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Fee0, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Fee0>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Fee0.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Fee0 records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Fee0, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Fee0> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Fee0.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Fee0 to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Fee0 fee0 = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Fee0)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Fee0 SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Fee0 fee0)
		{
			return fee0;
		}
	}
	
	/// <summary>
	/// This class provides the IsCleared data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class IsCleared : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.IsCleared, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.IsCleared> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static IsCleared()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.IsCleared.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.IsCleared, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.IsCleared>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.IsCleared.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.IsCleared records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.IsCleared, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.IsCleared> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.IsCleared.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.IsCleared to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.IsCleared isCleared = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.IsCleared)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.IsCleared SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.IsCleared isCleared)
		{
			return isCleared;
		}
	}
	
	/// <summary>
	/// This class provides the Memo0 data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class Memo0 : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo0, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo0> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static Memo0()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo0.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo0, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo0>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo0.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo0 records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo0, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo0> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo0.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo0 to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo0 memo0 = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo0)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo0 SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo0 memo0)
		{
			return memo0;
		}
	}
	
	/// <summary>
	/// This class provides the Memo1 data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class Memo1 : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo1, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo1> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static Memo1()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo1.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo1, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo1>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo1.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo1 records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo1, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo1> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo1.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo1 to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo1 memo1 = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo1)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo1 SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo1 memo1)
		{
			return memo1;
		}
	}
	
	/// <summary>
	/// This class provides the Memo2 data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class Memo2 : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo2, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo2> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static Memo2()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo2.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo2, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo2>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo2.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo2 records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo2, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo2> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo2.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo2 to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo2 memo2 = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo2)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo2 SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo2 memo2)
		{
			return memo2;
		}
	}
	
	/// <summary>
	/// This class provides the ModifiedDateTime data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class ModifiedDateTime : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedDateTime, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedDateTime> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static ModifiedDateTime()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedDateTime.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedDateTime, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedDateTime>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedDateTime.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedDateTime records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedDateTime, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedDateTime> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedDateTime.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedDateTime to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedDateTime modifiedDateTime = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedDateTime)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedDateTime SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedDateTime modifiedDateTime)
		{
			return modifiedDateTime;
		}
	}
	
	/// <summary>
	/// This class provides the ModifiedUserId data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class ModifiedUserId : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedUserId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedUserId> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static ModifiedUserId()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedUserId.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedUserId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedUserId>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedUserId.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedUserId records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedUserId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedUserId> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedUserId.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedUserId to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedUserId modifiedUserId = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedUserId)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedUserId SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedUserId modifiedUserId)
		{
			return modifiedUserId;
		}
	}
	
	/// <summary>
	/// This class provides the SelectRow data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class SelectRow : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.SelectRow, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.SelectRow> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static SelectRow()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.SelectRow.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.SelectRow, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.SelectRow>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.SelectRow.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.SelectRow records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.SelectRow, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.SelectRow> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.SelectRow.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.SelectRow to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.SelectRow selectRow = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.SelectRow)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.SelectRow SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.SelectRow selectRow)
		{
			return selectRow;
		}
	}
	
	/// <summary>
	/// This class provides the StatusId data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class StatusId : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.StatusId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.StatusId> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static StatusId()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.StatusId.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.StatusId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.StatusId>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.StatusId.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.StatusId records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.StatusId, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.StatusId> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.StatusId.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.StatusId to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.StatusId statusId = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.StatusId)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.StatusId SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.StatusId statusId)
		{
			return statusId;
		}
	}
	
	/// <summary>
	/// This class provides the TrackingNumber data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class TrackingNumber : FluidTrade.Core.IContent
	{
		
		internal object key;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.TrackingNumber, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.TrackingNumber> selectSelf;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static TrackingNumber()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.TrackingNumber.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.TrackingNumber, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.TrackingNumber>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.TrackingNumber.SelectFromSelf);
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.TrackingNumber records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.TrackingNumber, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.TrackingNumber> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.TrackingNumber.selectSelf;
			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.TrackingNumber to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.TrackingNumber trackingNumber = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.TrackingNumber)(iContent));
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.TrackingNumber SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.TrackingNumber trackingNumber)
		{
			return trackingNumber;
		}
	}
	
	/// <summary>
	/// This class provides the PaymentHeader data for a report.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("FluidTrade.PresentationGenerator.PresentationGenerator", "1.3.0.0")]
	[global::System.ComponentModel.DesignerCategoryAttribute("code")]
	[global::System.ComponentModel.ToolboxItemAttribute(true)]
	public class PaymentHeader : FluidTrade.Core.IContent
	{
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActiveFlag activeFlag;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentDate actualPaymentDate;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentValue actualPaymentValue;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CheckId checkId;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ClearedDate clearedDate;
		
		private FluidTrade.Core.ComplexComparer<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary> comparer;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedDateTime createdDateTime;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedUserId createdUserId;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentDate effectivePaymentDate;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentValue effectivePaymentValue;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Fee0 fee0;
		
		private FluidTrade.Core.ComplexFilter<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary> filter;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.IsCleared isCleared;
		
		internal object key;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo0 memo0;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo1 memo1;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo2 memo2;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedDateTime modifiedDateTime;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedUserId modifiedUserId;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary[] paymentList;
		
		private FluidTrade.Core.ComplexFilter<FluidTrade.Guardian.ConsumerTrustPaymentRow> prefilter;
		
		private System.Func<FluidTrade.Guardian.ConsumerTrustPaymentRow, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary> selector;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.SelectRow selectRow;
		
		private static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.PaymentHeader, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.PaymentHeader> selectSelf;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.StatusId statusId;
		
		internal FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.TrackingNumber trackingNumber;
		
		/// <summary>
		/// Creates the static resources required for this class.
		/// </summary>
		static PaymentHeader()
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.PaymentHeader.selectSelf = new System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.PaymentHeader, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.PaymentHeader>(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.PaymentHeader.SelectFromSelf);
		}
		
		/// <summary>
		/// Creates a FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.PaymentHeader.
		/// </summary>
		public PaymentHeader()
		{
			this.activeFlag = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActiveFlag();
			this.actualPaymentDate = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentDate();
			this.actualPaymentValue = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentValue();
			this.checkId = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CheckId();
			this.clearedDate = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ClearedDate();
			this.createdDateTime = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedDateTime();
			this.createdUserId = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedUserId();
			this.effectivePaymentDate = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentDate();
			this.effectivePaymentValue = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentValue();
			this.fee0 = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Fee0();
			this.isCleared = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.IsCleared();
			this.memo0 = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo0();
			this.memo1 = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo1();
			this.memo2 = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo2();
			this.modifiedDateTime = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedDateTime();
			this.modifiedUserId = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedUserId();
			this.selectRow = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.SelectRow();
			this.statusId = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.StatusId();
			this.trackingNumber = new FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.TrackingNumber();
		}
		
		/// <summary>
		/// ActiveFlag
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActiveFlag ActiveFlag
		{
			get
			{
				return this.activeFlag;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// ActualPaymentDate
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentDate ActualPaymentDate
		{
			get
			{
				return this.actualPaymentDate;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// ActualPaymentValue
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ActualPaymentValue ActualPaymentValue
		{
			get
			{
				return this.actualPaymentValue;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// CheckId
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CheckId CheckId
		{
			get
			{
				return this.checkId;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// ClearedDate
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ClearedDate ClearedDate
		{
			get
			{
				return this.clearedDate;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the complex comparison for ordering records from the result set.
		/// </summary>
		public FluidTrade.Core.ComplexComparer<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary> Comparer
		{
			get
			{
				return this.comparer;
			}
			set
			{
				this.comparer = value;
			}
		}
		
		/// <summary>
		/// CreatedDateTime
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedDateTime CreatedDateTime
		{
			get
			{
				return this.createdDateTime;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// CreatedUserId
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.CreatedUserId CreatedUserId
		{
			get
			{
				return this.createdUserId;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// EffectivePaymentDate
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentDate EffectivePaymentDate
		{
			get
			{
				return this.effectivePaymentDate;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// EffectivePaymentValue
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.EffectivePaymentValue EffectivePaymentValue
		{
			get
			{
				return this.effectivePaymentValue;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Fee0
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Fee0 Fee0
		{
			get
			{
				return this.fee0;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the complex filter used to remove records from the result set.
		/// </summary>
		public FluidTrade.Core.ComplexFilter<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary> Filter
		{
			get
			{
				return this.filter;
			}
			set
			{
				this.filter = value;
			}
		}
		
		/// <summary>
		/// IsCleared
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.IsCleared IsCleared
		{
			get
			{
				return this.isCleared;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the unique identifier of this content.
		/// </summary>
		public object Key
		{
			get
			{
				return this.key;
			}
			set
			{
				this.key = value;
			}
		}
		
		/// <summary>
		/// Memo0
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo0 Memo0
		{
			get
			{
				return this.memo0;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Memo1
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo1 Memo1
		{
			get
			{
				return this.memo1;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Memo2
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.Memo2 Memo2
		{
			get
			{
				return this.memo2;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// ModifiedDateTime
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedDateTime ModifiedDateTime
		{
			get
			{
				return this.modifiedDateTime;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// ModifiedUserId
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.ModifiedUserId ModifiedUserId
		{
			get
			{
				return this.modifiedUserId;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// PaymentList
		/// </summary>
		public System.Collections.Generic.IEnumerable<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary> PaymentList
		{
			get
			{
				return this.paymentList;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets or sets the complex filter used to remove records from the result set.
		/// </summary>
		public FluidTrade.Core.ComplexFilter<FluidTrade.Guardian.ConsumerTrustPaymentRow> Prefilter
		{
			get
			{
				return this.prefilter;
			}
			set
			{
				this.prefilter = value;
			}
		}
		
		/// <summary>
		/// Gets or sets the delegate used to select a destination record from a source.
		/// </summary>
		public System.Func<FluidTrade.Guardian.ConsumerTrustPaymentRow, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary> Selector
		{
			get
			{
				return this.selector;
			}
			set
			{
				this.selector = value;
			}
		}
		
		/// <summary>
		/// SelectRow
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.SelectRow SelectRow
		{
			get
			{
				return this.selectRow;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Gets the selector delegate for FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.PaymentHeader records.
		/// </summary>
		public static System.Func<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.PaymentHeader, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.PaymentHeader> SelectSelf
		{
			get
			{
				return FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.PaymentHeader.selectSelf;
			}
		}
		
		/// <summary>
		/// StatusId
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.StatusId StatusId
		{
			get
			{
				return this.statusId;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// TrackingNumber
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.TrackingNumber TrackingNumber
		{
			get
			{
				return this.trackingNumber;
			}
			set
			{

			}
		}
		
		/// <summary>
		/// Copies one FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.PaymentHeader to another.
		/// </summary>
		public void Copy(FluidTrade.Core.IContent iContent)
		{
			FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.PaymentHeader paymentHeader = ((FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.PaymentHeader)(iContent));
			this.activeFlag.Copy(paymentHeader.activeFlag);
			this.actualPaymentDate.Copy(paymentHeader.actualPaymentDate);
			this.actualPaymentValue.Copy(paymentHeader.actualPaymentValue);
			this.checkId.Copy(paymentHeader.checkId);
			this.clearedDate.Copy(paymentHeader.clearedDate);
			this.createdDateTime.Copy(paymentHeader.createdDateTime);
			this.createdUserId.Copy(paymentHeader.createdUserId);
			this.effectivePaymentDate.Copy(paymentHeader.effectivePaymentDate);
			this.effectivePaymentValue.Copy(paymentHeader.effectivePaymentValue);
			this.fee0.Copy(paymentHeader.fee0);
			this.isCleared.Copy(paymentHeader.isCleared);
			this.memo0.Copy(paymentHeader.memo0);
			this.memo1.Copy(paymentHeader.memo1);
			this.memo2.Copy(paymentHeader.memo2);
			this.modifiedDateTime.Copy(paymentHeader.modifiedDateTime);
			this.modifiedUserId.Copy(paymentHeader.modifiedUserId);
			this.selectRow.Copy(paymentHeader.selectRow);
			this.statusId.Copy(paymentHeader.statusId);
			this.trackingNumber.Copy(paymentHeader.trackingNumber);
		}
		
		/// <summary>
		/// Creates a FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.PaymentHeader.
		/// </summary>
		public FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.PaymentHeader Select(System.Guid guid)
		{
			this.key = guid;
			System.Collections.Generic.IEnumerable<FluidTrade.Guardian.ConsumerTrustPaymentRow> ebee1cf6632e442b08f41279090b969b0 = System.Linq.Enumerable.Where<FluidTrade.Guardian.ConsumerTrustPaymentRow>(DataModel.ConsumerTrustPayment, this.prefilter.Filter);
			System.Collections.Generic.IEnumerable<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary> q6e7eb7d8c8c742f5906d73e1db3b751c = System.Linq.Enumerable.Select<FluidTrade.Guardian.ConsumerTrustPaymentRow, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary>(ebee1cf6632e442b08f41279090b969b0, this.selector);
			System.Collections.Generic.IEnumerable<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary> x3758ffaf5e93420ebccbd8e6fa59e3ee = System.Linq.Enumerable.Where<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary>(q6e7eb7d8c8c742f5906d73e1db3b751c, this.filter.Filter);
			System.Collections.Generic.IEnumerable<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary> a17f76ffbb58c41308a581e1d6ee1813d = System.Linq.Enumerable.OrderBy<FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary>(x3758ffaf5e93420ebccbd8e6fa59e3ee, FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummary.PaymentSummary.SelectSelf, this.comparer);
			this.paymentList = System.Linq.Enumerable.ToArray(a17f76ffbb58c41308a581e1d6ee1813d);
			return this;
		}
		
		/// <summary>
		/// Selects a record from itself.
		/// </summary>
		private static FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.PaymentHeader SelectFromSelf(FluidTrade.Guardian.Schema.DebtNegotiatorPaymentSummaryHeader.PaymentHeader paymentHeader)
		{
			return paymentHeader;
		}
	}
}
