rm -force "${Home}\Documents\Visual Studio 2008\Projects\Fluid Trade Utilities\Setup\Alternate Debt Working Order.xaml"
cp -force "${Home}\Documents\Visual Studio 2008\Projects\Fluid Trade\Guardian\Database\Reports\Alternate Debt Working Order.xaml" -destination "${Home}\Documents\Visual Studio 2008\Projects\Fluid Trade Utilities\Setup\"
rm -force "${Home}\Documents\Visual Studio 2008\Projects\Fluid Trade Utilities\Setup\Classic Debt Working Order.xaml"
cp -force "${Home}\Documents\Visual Studio 2008\Projects\Fluid Trade\Guardian\Database\Reports\Classic Debt Working Order.xaml" -destination "${Home}\Documents\Visual Studio 2008\Projects\Fluid Trade Utilities\Setup\"
rm -force "${Home}\Documents\Visual Studio 2008\Projects\Fluid Trade Utilities\Setup\Debt Working Order.xaml"
cp -force "${Home}\Documents\Visual Studio 2008\Projects\Fluid Trade\Guardian\Database\Reports\Debt Working Order.xaml" -destination "${Home}\Documents\Visual Studio 2008\Projects\Fluid Trade Utilities\Setup\"
rm -force "${Home}\Documents\Visual Studio 2008\Projects\Fluid Trade Utilities\Setup\Ingrid Yeoh Orders.xml"
cp -force "${Home}\Documents\Visual Studio 2008\Projects\Fluid Trade\Guardian\Database\Unit Test\Ingrid Yeoh Orders.xml" -destination "${Home}\Documents\Visual Studio 2008\Projects\Fluid Trade Utilities\Setup\"
rm -force "${Home}\Documents\Visual Studio 2008\Projects\Fluid Trade Utilities\Setup\Kai Hitori Orders.xml"
cp -force "${Home}\Documents\Visual Studio 2008\Projects\Fluid Trade\Guardian\Database\Unit Test\Kai Hitori Orders.xml" -destination "${Home}\Documents\Visual Studio 2008\Projects\Fluid Trade Utilities\Setup\"
rm -force "${Home}\Documents\Visual Studio 2008\Projects\Fluid Trade Utilities\Setup\Karen Holden Orders.xml"
cp -force "${Home}\Documents\Visual Studio 2008\Projects\Fluid Trade\Guardian\Database\Unit Test\Karen Holden Orders.xml" -destination "${Home}\Documents\Visual Studio 2008\Projects\Fluid Trade Utilities\Setup\"
